# Generated by Django 3.0 on 2020-04-20 02:34

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(upload_to=team.models.custom_upload_to),
        ),
    ]
