# Generated by Django 3.0 on 2020-04-20 03:30

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200419_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-name'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(upload_to=team.models.custom_upload_to, verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(max_length=50, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
    ]
