# Generated by Django 3.0 on 2020-04-20 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-name'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='cooperative',
            options={'ordering': ['-name'], 'verbose_name': 'Cooperativa', 'verbose_name_plural': 'Cooperativas'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['hour'], 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Salida', 'verbose_name_plural': 'Salidas'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='fax',
            field=models.CharField(max_length=50, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='mail',
            field=models.EmailField(max_length=200, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='phone2',
            field=models.CharField(max_length=50, verbose_name='Otros teléfonos'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Cooperative', verbose_name='Cooperativa'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='transport.City', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='isactive',
            field=models.BooleanField(verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='transport.City', verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='route',
            field=models.CharField(max_length=200, verbose_name='Ruta'),
        ),
    ]
